spring.datasource.platform=mysql
db.num=1
db.url.0=jdbc:mysql://mysql:3306/sparion-nacos?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
db.user=root
db.password=123456

nacos.naming.empty-service.auto-clean=true
nacos.naming.empty-service.clean.initial-delay-ms=50000
nacos.naming.empty-service.clean.period-time-ms=30000

management.endpoints.web.exposure.include=*

management.metrics.export.elastic.enabled=false
management.metrics.export.influx.enabled=false

server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i

server.tomcat.basedir=/home/sparion/nacos/tomcat/logs

nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-ui/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

# 设置超级管理员用户名和密码
nacos.core.auth.super.admin=nacos
nacos.core.auth.super.password=nacos

# 开启控制台登录鉴权
nacos.core.auth.enable.consoleAuth=true
nacos.core.auth.system.type=nacos

# 开启认证鉴权
nacos.core.auth.enabled=true
nacos.core.auth.plugin.nacos.token.expire.seconds=18000
nacos.core.auth.plugin.nacos.token.secret.key=bpnSeSh8pH8pt1FMp0L4FmfbsmlJqAvqCRJrFy5KQAz6LaP4iRdPRwJmI8Y5udolZtw9WZye6hZyHSaxD1N6y0giGlREo4pgmv3WWrQXkRavXmjF78hf6xbGSz2gzSO5ah1RlzzX9aNtCJntutPKOQhMrbA2yrLMlO5b7D6ky10MzBg8wT9bWF1pGI09WBVuVdQiEjfyg3UtmjA6dp4Cbo1SwCzkOBt1pFLM7QSgOeXpeHCgEY4kQzv7UBvzCKWm
nacos.core.auth.plugin.nacos.token.cache.enable=true
nacos.core.auth.enable.userAgentAuthWhite=false
nacos.core.auth.server.identity.key=serverIdentity
nacos.core.auth.server.identity.value=security

nacos.istio.mcp.server.enabled=false
