version: '3.8'

services:
  mysql:
    image: mysql:8.4.3
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - sparion_network

  redis:
    image: redis:7.4.2
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - sparion_network

  nacos:
    image: nacos/nacos-server:v2.4.3
    container_name: nacos
    hostname: nacos
    environment:
      MODE: standalone
    volumes:
      - ./nacos/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      - sparion_network

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=12345678
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - sparion_network

networks:
  sparion_network:
    driver: bridge