spring:
  application:
    name: ${sparion.application.sparion-external-server}
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
  config:
    import: nacos:sparion-common.properties,nacos:sparion-redis.properties
server:
  port: 16000
