# jwt
jwt.subject=sparion
jwt.secret-key=wpFudcbry3tdCY8h2?Fk$A,+yxd.ZHR/7-aFZRpGrKWYTN!h:|JvS4.KNU;,EC,=kZPZKu&hjUZ<G$n;R<ESfAKCa7&GW,;TjG?%VuDy/ZvKtRr<f5&uj_*?3D*<PKV_Rkf&$:+$FRK3k?/y.Z,cc7!!6*ZH|%xPy<-p_/-c6$|3CjQRQvuMp/ABEn,*7phuNCWc$;!4>hv%Fpka<G/,nrpn5Rp:KS3DQK52.p|Y.hTuHkTMcJr88r5&&CmevVQ4
jwt.expiration-time=30
jwt.refresh-secret-key=p.un%8*?yCd6vpVyB3<K;BJcGe2!Z$Sj*EJxH6Zd./SfajTdQQTCJr:BpHj3?v;FSPr+Hss*N5>S/5.uHkdrz,z=Je8x<Nf>JDW_YCy,z@4uW&QK%xyy:fdc3vM<b?M53QAQZ*P5RQ_Av&Vmj:Vb<dwn:2=zkPJnWd=+Zttb%|xQ=mRpCy45,5CjUKuCZWFQn6a,KCV8&<X7Rc5k;yK>?%s5?HUC_kTe.Hju$cvmD|&A%K8|&RAha6WwYtnDyteQ
jwt.refresh-expiration-time=10080

# 网关认证头
security.allow-header=x-forward-gateway
security.allow-header-value=sparion-gateway

# 微服务名称
sparion.applications.sparion-gateway=sparion-gateway
sparion.applications.sparion-auth=sparion-auth
sparion.applications.sparion-module-system=sparion-module-system

# 开启虚拟线程支持
spring.threads.virtual.enabled=true