spring.cloud.gateway.routes[0].id=sparion-auth
spring.cloud.gateway.routes[0].uri=lb://${sparion.applications.sparion-auth}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[0].filters[0]=AddRequestHeadersIfNotPresent=${security.allow-header}:${security.allow-header-value}
spring.cloud.gateway.routes[0].filters[1]=RewritePath=/api/auth/(?<segment>.*), /auth/$\{segment}
spring.cloud.gateway.routes[1].id=sparion-module-system
spring.cloud.gateway.routes[1].uri=lb://${sparion.applications.sparion-module-system}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/system/**
spring.cloud.gateway.routes[1].filters[0]=AddRequestHeadersIfNotPresent=${security.allow-header}:${security.allow-header-value}
spring.cloud.gateway.routes[1].filters[1]=RewritePath=/api/system/(?<segment>.*), /system/$\{segment}
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.http.server.reactive=DEBUG