spring:
  application:
    name: sparion-module-system
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  config:
    import: nacos:sparion-module-system.properties,nacos:sparion-redis.properties,nacos:sparion-common.properties
server:
  port: 13000